name: Unit testing of the Framework

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image:  google/dart:latest

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
    - uses: subosito/flutter-action@v1.1.1
      with:
        channel: 'stable'
        flutter-version: 1.12.13+hotfix.5
    - run: flutter pub get
    - name: Run tests
    - run: flutter test
